grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3
model_selection:
  module_0:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
      - 6